#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
UI Automation Recorder - Robust Version
超鲁棒版本：生成高可靠性的自动化代码

鲁棒性增强：
1. 自动重试机制（可配置次数）
2. 智能等待策略（元素可见、启用、可交互）
3. 多种点击策略（Click → ClickInput → SendKeys）
4. 失败截图保存
5. 详细日志记录（支持文件日志）
6. 元素状态验证
7. 窗口焦点自动恢复
8. 异常恢复机制
9. 超时保护
10. 操作前后验证

依赖安装：
pip install uiautomation PyQt5 pynput pyperclip pillow
"""

import sys
import time
from datetime import datetime
from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout,
                             QHBoxLayout, QPushButton, QTextEdit, QLabel,
                             QSplitter, QGroupBox, QCheckBox, QSpinBox,
                             QFileDialog, QMessageBox, QListWidget, QComboBox)
from PyQt5.QtCore import Qt, QThread, pyqtSignal
from PyQt5.QtGui import QFont

import uiautomation as auto
from pynput import mouse, keyboard
import pyperclip


class RobustCodeGenerator:
    """生成超鲁棒的自动化代码"""

    @staticmethod
    def generate_robust_header() -> list:
        """生成鲁棒性框架代码"""
        lines = []

        lines.append("#!/usr/bin/env python3")
        lines.append("# -*- coding: utf-8 -*-")
        lines.append(f"# Generated by UI Automation Recorder - Robust Version")
        lines.append(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        lines.append("import uiautomation as auto")
        lines.append("import time")
        lines.append("import logging")
        lines.append("from datetime import datetime")
        lines.append("from pathlib import Path")
        lines.append("")

        # 日志配置
        lines.append("# ========== 日志配置 ==========")
        lines.append("log_dir = Path('automation_logs')")
        lines.append("log_dir.mkdir(exist_ok=True)")
        lines.append("log_file = log_dir / f'automation_{datetime.now().strftime(\"%Y%m%d_%H%M%S\")}.log'")
        lines.append("")
        lines.append("logging.basicConfig(")
        lines.append("    level=logging.INFO,")
        lines.append("    format='%(asctime)s [%(levelname)s] %(message)s',")
        lines.append("    handlers=[")
        lines.append("        logging.FileHandler(log_file, encoding='utf-8'),")
        lines.append("        logging.StreamHandler()")
        lines.append("    ]")
        lines.append(")")
        lines.append("logger = logging.getLogger(__name__)")
        lines.append("")

        # 全局配置
        lines.append("# ========== 全局配置 ==========")
        lines.append("auto.uiautomation.SetGlobalSearchTimeout(10)")
        lines.append("")
        lines.append("class Config:")
        lines.append("    MAX_RETRY = 3  # 最大重试次数")
        lines.append("    RETRY_DELAY = 1.0  # 重试间隔（秒）")
        lines.append("    WAIT_TIMEOUT = 10  # 等待超时（秒）")
        lines.append("    OPERATION_DELAY = 0.5  # 操作间隔（秒）")
        lines.append("    SCREENSHOT_ON_ERROR = True  # 失败时截图")
        lines.append("    SCREENSHOT_DIR = Path('error_screenshots')")
        lines.append("")
        lines.append("Config.SCREENSHOT_DIR.mkdir(exist_ok=True)")
        lines.append("")

        return lines

    @staticmethod
    def generate_utility_functions() -> list:
        """生成实用工具函数"""
        lines = []

        # 截图函数
        lines.append("def capture_screenshot(name='error'):")
        lines.append('    """捕获当前屏幕截图"""')
        lines.append("    if not Config.SCREENSHOT_ON_ERROR:")
        lines.append("        return None")
        lines.append("    try:")
        lines.append("        from PIL import ImageGrab")
        lines.append("        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')")
        lines.append("        filename = Config.SCREENSHOT_DIR / f'{name}_{timestamp}.png'")
        lines.append("        screenshot = ImageGrab.grab()")
        lines.append("        screenshot.save(filename)")
        lines.append("        logger.info(f'截图已保存: {filename}')")
        lines.append("        return str(filename)")
        lines.append("    except Exception as e:")
        lines.append("        logger.warning(f'截图失败: {e}')")
        lines.append("        return None")
        lines.append("")

        # 等待元素函数
        lines.append("def wait_for_element(control, timeout=None):")
        lines.append('    """智能等待元素准备就绪"""')
        lines.append("    if timeout is None:")
        lines.append("        timeout = Config.WAIT_TIMEOUT")
        lines.append("    ")
        lines.append("    start_time = time.time()")
        lines.append("    ")
        lines.append("    # 1. 等待元素存在")
        lines.append("    if not control.Exists(maxSearchSeconds=timeout):")
        lines.append("        raise Exception(f'元素不存在（超时 {timeout}s）')")
        lines.append("    ")
        lines.append("    # 2. 等待元素可见")
        lines.append("    while time.time() - start_time < timeout:")
        lines.append("        try:")
        lines.append("            if control.IsOffscreen:")
        lines.append("                control.ScrollIntoView()")
        lines.append("            break")
        lines.append("        except:")
        lines.append("            time.sleep(0.1)")
        lines.append("    ")
        lines.append("    # 3. 等待元素启用")
        lines.append("    while time.time() - start_time < timeout:")
        lines.append("        try:")
        lines.append("            if control.IsEnabled:")
        lines.append("                break")
        lines.append("        except:")
        lines.append("            pass")
        lines.append("        time.sleep(0.1)")
        lines.append("    else:")
        lines.append("        logger.warning('元素未启用，但将继续尝试')")
        lines.append("    ")
        lines.append("    time.sleep(0.2)  # 额外的稳定延迟")
        lines.append("    return True")
        lines.append("")

        # 查找控件函数（带重试）
        lines.append("def find_control_robust(window, locators, name='control'):")
        lines.append('    """使用多种定位器查找控件（带重试）"""')
        lines.append("    control = None")
        lines.append("    last_error = None")
        lines.append("    ")
        lines.append("    for retry in range(Config.MAX_RETRY):")
        lines.append("        for i, locator_info in enumerate(locators, 1):")
        lines.append("            try:")
        lines.append("                logger.debug(f'尝试定位器 {i}/{len(locators)}: {locator_info[\"desc\"]}')")
        lines.append("                control = window.Control(**locator_info['params'])")
        lines.append("                ")
        lines.append("                # 验证控件存在")
        lines.append("                if control.Exists(maxSearchSeconds=2):")
        lines.append("                    logger.info(f'✅ 找到控件 \"{name}\" (方法 {i}: {locator_info[\"desc\"]})')")
        lines.append("                    return control")
        lines.append("            except Exception as e:")
        lines.append("                last_error = e")
        lines.append("                continue")
        lines.append("        ")
        lines.append("        # 所有定位器都失败，重试")
        lines.append("        if retry < Config.MAX_RETRY - 1:")
        lines.append("            logger.warning(f'定位失败，{Config.RETRY_DELAY}秒后重试 ({retry+1}/{Config.MAX_RETRY})')")
        lines.append("            time.sleep(Config.RETRY_DELAY)")
        lines.append("            window.SetFocus()  # 尝试重新聚焦窗口")
        lines.append("    ")
        lines.append("    # 所有尝试都失败")
        lines.append("    error_msg = f'无法定位控件 \"{name}\" (尝试 {Config.MAX_RETRY} 次, {len(locators)} 种方法)'")
        lines.append("    logger.error(error_msg)")
        lines.append("    capture_screenshot(f'find_control_failed_{name}')")
        lines.append("    raise Exception(error_msg)")
        lines.append("")

        # 鲁棒点击函数
        lines.append("def click_robust(control, name='control', action='click'):")
        lines.append('    """超鲁棒点击函数（多种策略）"""')
        lines.append("    strategies = [")
        lines.append("        ('Click', lambda: control.Click(simulateMove=False)),")
        lines.append("        ('Click with move', lambda: control.Click(simulateMove=True)),")
        lines.append("        ('ClickInput', lambda: control.ClickInput()),")
        lines.append("        ('SendKeys ENTER', lambda: control.SendKeys('{ENTER}'))")
        lines.append("    ]")
        lines.append("    ")
        lines.append("    if action == 'double_click':")
        lines.append("        strategies = [")
        lines.append("            ('DoubleClick', lambda: control.DoubleClick(simulateMove=False)),")
        lines.append("            ('DoubleClick with move', lambda: control.DoubleClick(simulateMove=True)),")
        lines.append("            ('Two Clicks', lambda: (control.Click(), time.sleep(0.1), control.Click()))")
        lines.append("        ]")
        lines.append("    elif action == 'right_click':")
        lines.append("        strategies = [")
        lines.append("            ('RightClick', lambda: control.RightClick(simulateMove=False)),")
        lines.append("            ('RightClick with move', lambda: control.RightClick(simulateMove=True))")
        lines.append("        ]")
        lines.append("    ")
        lines.append("    for retry in range(Config.MAX_RETRY):")
        lines.append("        for strategy_name, strategy_func in strategies:")
        lines.append("            try:")
        lines.append("                logger.debug(f'尝试点击策略: {strategy_name}')")
        lines.append("                ")
        lines.append("                # 等待元素准备就绪")
        lines.append("                wait_for_element(control)")
        lines.append("                ")
        lines.append("                # 设置焦点")
        lines.append("                try:")
        lines.append("                    control.SetFocus()")
        lines.append("                    time.sleep(0.1)")
        lines.append("                except:")
        lines.append("                    pass")
        lines.append("                ")
        lines.append("                # 执行点击")
        lines.append("                strategy_func()")
        lines.append("                time.sleep(0.2)")
        lines.append("                ")
        lines.append("                logger.info(f'✅ {action} 成功: \"{name}\" (策略: {strategy_name})')")
        lines.append("                return True")
        lines.append("            except Exception as e:")
        lines.append("                logger.debug(f'{strategy_name} 失败: {e}')")
        lines.append("                continue")
        lines.append("        ")
        lines.append("        # 所有策略都失败，重试")
        lines.append("        if retry < Config.MAX_RETRY - 1:")
        lines.append("            logger.warning(f'点击失败，{Config.RETRY_DELAY}秒后重试 ({retry+1}/{Config.MAX_RETRY})')")
        lines.append("            time.sleep(Config.RETRY_DELAY)")
        lines.append("    ")
        lines.append("    # 所有尝试都失败")
        lines.append("    error_msg = f'{action} 失败: \"{name}\" (尝试 {Config.MAX_RETRY} 次)'")
        lines.append("    logger.error(error_msg)")
        lines.append("    capture_screenshot(f'{action}_failed_{name}')")
        lines.append("    raise Exception(error_msg)")
        lines.append("")

        # 鲁棒输入函数
        lines.append("def send_keys_robust(control, text, name='control'):")
        lines.append('    """超鲁棒输入函数"""')
        lines.append("    strategies = [")
        lines.append("        ('SendKeys', lambda: control.SendKeys(text, interval=0.01)),")
        lines.append("        ('SendKeys slow', lambda: control.SendKeys(text, interval=0.05)),")
        lines.append("        ('SetValue', lambda: control.GetValuePattern().SetValue(text)),")
        lines.append("        ('Type char by char', lambda: [control.SendKeys(c, interval=0.05) for c in text])")
        lines.append("    ]")
        lines.append("    ")
        lines.append("    for retry in range(Config.MAX_RETRY):")
        lines.append("        for strategy_name, strategy_func in strategies:")
        lines.append("            try:")
        lines.append("                logger.debug(f'尝试输入策略: {strategy_name}')")
        lines.append("                ")
        lines.append("                # 等待元素准备就绪")
        lines.append("                wait_for_element(control)")
        lines.append("                ")
        lines.append("                # 设置焦点并清空")
        lines.append("                control.SetFocus()")
        lines.append("                time.sleep(0.1)")
        lines.append("                ")
        lines.append("                # 清空现有内容")
        lines.append("                try:")
        lines.append("                    control.SendKeys('{Ctrl}a', interval=0)")
        lines.append("                    time.sleep(0.05)")
        lines.append("                    control.SendKeys('{Delete}', interval=0)")
        lines.append("                    time.sleep(0.1)")
        lines.append("                except:")
        lines.append("                    pass")
        lines.append("                ")
        lines.append("                # 执行输入")
        lines.append("                strategy_func()")
        lines.append("                time.sleep(0.2)")
        lines.append("                ")
        lines.append("                # 验证输入（可选）")
        lines.append("                try:")
        lines.append("                    actual_value = control.GetValuePattern().Value")
        lines.append("                    if text in actual_value or actual_value in text:")
        lines.append("                        logger.info(f'✅ 输入成功: \"{name}\" = \"{text[:50]}...\" (策略: {strategy_name})')")
        lines.append("                        return True")
        lines.append("                except:")
        lines.append("                    # 无法验证，假设成功")
        lines.append("                    logger.info(f'✅ 输入完成: \"{name}\" = \"{text[:50]}...\" (策略: {strategy_name})')")
        lines.append("                    return True")
        lines.append("            except Exception as e:")
        lines.append("                logger.debug(f'{strategy_name} 失败: {e}')")
        lines.append("                continue")
        lines.append("        ")
        lines.append("        # 所有策略都失败，重试")
        lines.append("        if retry < Config.MAX_RETRY - 1:")
        lines.append("            logger.warning(f'输入失败，{Config.RETRY_DELAY}秒后重试 ({retry+1}/{Config.MAX_RETRY})')")
        lines.append("            time.sleep(Config.RETRY_DELAY)")
        lines.append("    ")
        lines.append("    # 所有尝试都失败")
        lines.append("    error_msg = f'输入失败: \"{name}\" (尝试 {Config.MAX_RETRY} 次)'")
        lines.append("    logger.error(error_msg)")
        lines.append("    capture_screenshot(f'send_keys_failed_{name}')")
        lines.append("    raise Exception(error_msg)")
        lines.append("")

        # 鲁棒获取窗口函数
        lines.append("def get_window_robust(window_name, locator_params):")
        lines.append('    """获取窗口（带重试）"""')
        lines.append("    for retry in range(Config.MAX_RETRY):")
        lines.append("        try:")
        lines.append("            logger.info(f'正在查找窗口: \"{window_name}\"')")
        lines.append("            window = auto.WindowControl(**locator_params)")
        lines.append("            ")
        lines.append("            if window.Exists(maxSearchSeconds=5):")
        lines.append("                window.SetFocus()")
        lines.append("                time.sleep(0.3)")
        lines.append("                logger.info(f'✅ 找到窗口: \"{window_name}\"')")
        lines.append("                return window")
        lines.append("        except Exception as e:")
        lines.append("            logger.debug(f'查找窗口失败: {e}')")
        lines.append("        ")
        lines.append("        if retry < Config.MAX_RETRY - 1:")
        lines.append("            logger.warning(f'未找到窗口，{Config.RETRY_DELAY}秒后重试 ({retry+1}/{Config.MAX_RETRY})')")
        lines.append("            time.sleep(Config.RETRY_DELAY)")
        lines.append("    ")
        lines.append("    error_msg = f'无法找到窗口: \"{window_name}\" (尝试 {Config.MAX_RETRY} 次)'")
        lines.append("    logger.error(error_msg)")
        lines.append("    capture_screenshot(f'window_not_found_{window_name}')")
        lines.append("    raise Exception(error_msg)")
        lines.append("")

        return lines

    @staticmethod
    def generate_locators_list(props: dict) -> list:
        """生成定位器参数列表"""
        locators = []

        # 方法 1: AutomationId
        if props.get('AutomationId'):
            locators.append({
                'desc': 'AutomationId',
                'params': {'AutomationId': props['AutomationId']}
            })

        # 方法 2: Name + ControlType
        if props.get('Name'):
            name = props['Name'].replace("'", "\\'")
            control_type = props.get('ControlType', '')
            locators.append({
                'desc': 'Name + ControlType',
                'params': {
                    'Name': name,
                    'ControlType': f"auto.ControlType.{control_type}Control"
                }
            })

        # 方法 3: ClassName + ControlType
        if props.get('ClassName'):
            control_type = props.get('ControlType', '')
            locators.append({
                'desc': 'ClassName + ControlType',
                'params': {
                    'ClassName': props['ClassName'],
                    'ControlType': f"auto.ControlType.{control_type}Control"
                }
            })

        return locators

    @staticmethod
    def generate_main_function(operations: list, use_robust: bool = True) -> list:
        """生成主函数"""
        lines = []

        lines.append("def main():")
        lines.append('    """主自动化流程"""')
        lines.append("    logger.info('='*60)")
        lines.append("    logger.info('开始执行自动化脚本')")
        lines.append("    logger.info('='*60)")
        lines.append("    ")
        lines.append("    start_time = time.time()")
        lines.append("    success_count = 0")
        lines.append("    error_count = 0")
        lines.append("    ")
        lines.append("    try:")

        # 按窗口分组
        window_groups = {}
        for op in operations:
            window_title = op['props'].get('window_title', 'Unknown')
            if window_title not in window_groups:
                window_groups[window_title] = []
            window_groups[window_title].append(op)

        step_num = 0
        for window_title, ops in window_groups.items():
            lines.append(f"        ")
            lines.append(f"        # {'='*50}")
            lines.append(f"        # 窗口: {window_title}")
            lines.append(f"        # {'='*50}")

            # 获取窗口
            escaped_title = window_title.replace("'", "\\'")
            lines.append(f"        window = get_window_robust(")
            lines.append(f"            '{escaped_title}',")
            lines.append(f"            {{'Name': '{escaped_title}'}}")
            lines.append(f"        )")
            lines.append(f"        ")

            # 处理每个操作
            for op in ops:
                step_num += 1
                action = op['action']
                props = op['props']
                control_name = props.get('Name', 'Unknown')

                lines.append(f"        # 步骤 {step_num}: {action} - {control_name}")
                lines.append(f"        try:")

                # 生成定位器
                locators = RobustCodeGenerator.generate_locators_list(props)
                lines.append(f"            locators = [")
                for loc in locators:
                    params_str = str(loc['params']).replace("'auto.ControlType.", "auto.ControlType.").replace("Control'", "Control")
                    lines.append(f"                {{'desc': '{loc['desc']}', 'params': {params_str}}},")
                lines.append(f"            ]")
                lines.append(f"            ")
                lines.append(f"            control = find_control_robust(window, locators, '{control_name}')")
                lines.append(f"            ")

                # 生成操作
                if action in ['click', 'double_click', 'right_click']:
                    lines.append(f"            click_robust(control, '{control_name}', '{action}')")
                elif action == 'type':
                    text = op.get('text', '')
                    escaped_text = text.replace("'", "\\'")
                    lines.append(f"            send_keys_robust(control, '{escaped_text}', '{control_name}')")

                lines.append(f"            time.sleep(Config.OPERATION_DELAY)")
                lines.append(f"            success_count += 1")
                lines.append(f"        except Exception as e:")
                lines.append(f"            logger.error(f'步骤 {step_num} 失败: {{e}}')")
                lines.append(f"            error_count += 1")
                lines.append(f"            # 继续执行后续步骤")
                lines.append(f"        ")

        lines.append("    except Exception as e:")
        lines.append("        logger.error(f'脚本执行异常: {e}')")
        lines.append("        import traceback")
        lines.append("        logger.error(traceback.format_exc())")
        lines.append("        capture_screenshot('fatal_error')")
        lines.append("    finally:")
        lines.append("        elapsed = time.time() - start_time")
        lines.append("        logger.info('='*60)")
        lines.append("        logger.info(f'脚本执行完成')")
        lines.append("        logger.info(f'成功: {success_count}, 失败: {error_count}, 耗时: {elapsed:.2f}秒')")
        lines.append("        logger.info(f'日志文件: {log_file}')")
        lines.append("        logger.info('='*60)")
        lines.append("")

        return lines

    @staticmethod
    def generate_complete_script(operations: list, max_retry: int = 3,
                                retry_delay: float = 1.0, operation_delay: float = 0.5) -> str:
        """生成完整的鲁棒脚本"""
        if not operations:
            return "# 没有录制到任何操作\n"

        lines = []

        # 头部
        lines.extend(RobustCodeGenerator.generate_robust_header())

        # 工具函数
        lines.extend(RobustCodeGenerator.generate_utility_functions())

        # 主函数
        lines.extend(RobustCodeGenerator.generate_main_function(operations))

        # 入口点
        lines.append("if __name__ == '__main__':")
        lines.append("    try:")
        lines.append("        # 可以在这里修改配置")
        lines.append(f"        Config.MAX_RETRY = {max_retry}")
        lines.append(f"        Config.RETRY_DELAY = {retry_delay}")
        lines.append(f"        Config.OPERATION_DELAY = {operation_delay}")
        lines.append("        ")
        lines.append("        main()")
        lines.append("    except KeyboardInterrupt:")
        lines.append("        logger.warning('用户中断执行')")
        lines.append("    except Exception as e:")
        lines.append("        logger.error(f'程序异常: {e}')")
        lines.append("        import traceback")
        lines.append("        traceback.print_exc()")

        return "\n".join(lines)


class RobustRecorderThread(QThread):
    """录制线程（同增强版）"""
    operation_detected = pyqtSignal(dict)
    status_changed = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.is_recording = False
        self.mouse_listener = None
        self.keyboard_listener = None
        self.typed_text_buffer = ""
        self.last_control_info = None
        self.last_click_time = 0
        self.click_threshold = 0.3

    def stop(self):
        self.is_recording = False
        if self.mouse_listener:
            self.mouse_listener.stop()
        if self.keyboard_listener:
            self.keyboard_listener.stop()
        self._flush_text_buffer()

    def run(self):
        self.is_recording = True
        self.mouse_listener = mouse.Listener(on_click=self.on_click)
        self.keyboard_listener = keyboard.Listener(on_press=self.on_press)
        self.mouse_listener.start()
        self.keyboard_listener.start()
        self.mouse_listener.join()
        self.keyboard_listener.join()

    def _flush_text_buffer(self):
        if self.typed_text_buffer and self.last_control_info:
            op = {
                'action': 'type',
                'text': self.typed_text_buffer,
                'props': self.last_control_info
            }
            self.operation_detected.emit(op)
            self.typed_text_buffer = ""

    def on_click(self, x, y, button, pressed):
        if not self.is_recording or not pressed:
            return

        with auto.UIAutomationInitializerInThread():
            self._flush_text_buffer()

            try:
                control = auto.ControlFromPoint(x, y)
                if not control:
                    return

                props = {
                    'Name': control.Name,
                    'AutomationId': control.AutomationId,
                    'ClassName': control.ClassName,
                    'ControlType': control.ControlTypeName,
                    'window_title': control.GetTopLevelControl().Name
                }
                self.last_control_info = props

                current_time = time.time()
                if button == mouse.Button.left:
                    if current_time - self.last_click_time < self.click_threshold:
                        action = 'double_click'
                    else:
                        action = 'click'
                    self.last_click_time = current_time
                elif button == mouse.Button.right:
                    action = 'right_click'
                else:
                    return

                op = {'action': action, 'props': props}
                self.operation_detected.emit(op)
                self.status_changed.emit(f"✅ 录制: {action} - {props.get('Name', 'Unknown')}")

            except Exception as e:
                self.status_changed.emit(f"⚠️ 错误: {str(e)[:50]}")

    def on_press(self, key):
        if not self.is_recording:
            return

        if key in [keyboard.Key.enter, keyboard.Key.tab]:
            self._flush_text_buffer()
        elif key == keyboard.Key.backspace:
            self.typed_text_buffer = self.typed_text_buffer[:-1]
        elif hasattr(key, 'char') and key.char:
            self.typed_text_buffer += key.char
        elif key == keyboard.Key.space:
            self.typed_text_buffer += ' '


class RobustRecorderWindow(QMainWindow):
    """超鲁棒录制器窗口"""

    def __init__(self):
        super().__init__()
        self.recorder_thread = None
        self.operations = []
        self.init_ui()

    def init_ui(self):
        self.setWindowTitle("UI Automation Recorder - Robust Version (超鲁棒版)")
        self.setGeometry(100, 100, 1400, 900)

        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QVBoxLayout(central_widget)

        # 控制面板
        control_panel = self.create_control_panel()
        main_layout.addWidget(control_panel)

        # 分割器
        splitter = QSplitter(Qt.Horizontal)
        left_panel = self.create_operations_panel()
        right_panel = self.create_code_panel()
        splitter.addWidget(left_panel)
        splitter.addWidget(right_panel)
        splitter.setSizes([400, 1000])
        main_layout.addWidget(splitter)

        self.statusBar().showMessage("就绪 - 超鲁棒版本（自动重试、智能等待、失败截图）")

    def create_control_panel(self):
        """创建控制面板"""
        group = QGroupBox("⚙️ 控制面板 - 鲁棒性配置")
        layout = QHBoxLayout()

        # 录制按钮
        self.start_btn = QPushButton("🔴 开始录制")
        self.start_btn.setStyleSheet("QPushButton { background-color: #4CAF50; color: white; font-weight: bold; padding: 8px; }")
        self.start_btn.clicked.connect(self.start_recording)

        self.stop_btn = QPushButton("⏸️ 停止录制")
        self.stop_btn.setEnabled(False)
        self.stop_btn.clicked.connect(self.stop_recording)

        layout.addWidget(self.start_btn)
        layout.addWidget(self.stop_btn)
        layout.addSpacing(20)

        # 鲁棒性配置
        layout.addWidget(QLabel("最大重试:"))
        self.max_retry_spin = QSpinBox()
        self.max_retry_spin.setRange(1, 10)
        self.max_retry_spin.setValue(3)
        self.max_retry_spin.valueChanged.connect(self.regenerate_code)
        layout.addWidget(self.max_retry_spin)

        layout.addWidget(QLabel("重试延迟(秒):"))
        self.retry_delay_spin = QSpinBox()
        self.retry_delay_spin.setRange(1, 10)
        self.retry_delay_spin.setValue(1)
        self.retry_delay_spin.valueChanged.connect(self.regenerate_code)
        layout.addWidget(self.retry_delay_spin)

        layout.addWidget(QLabel("操作延迟(秒):"))
        self.operation_delay_spin = QSpinBox()
        self.operation_delay_spin.setRange(0, 5)
        self.operation_delay_spin.setValue(1)
        self.operation_delay_spin.valueChanged.connect(self.regenerate_code)
        layout.addWidget(self.operation_delay_spin)

        layout.addStretch()

        # 操作按钮
        copy_btn = QPushButton("📋 复制代码")
        copy_btn.clicked.connect(self.copy_code)

        save_btn = QPushButton("💾 保存代码")
        save_btn.clicked.connect(self.save_code)

        clear_btn = QPushButton("🗑️ 清空")
        clear_btn.clicked.connect(self.clear_operations)

        layout.addWidget(copy_btn)
        layout.addWidget(save_btn)
        layout.addWidget(clear_btn)

        group.setLayout(layout)
        return group

    def create_operations_panel(self):
        """创建操作列表面板"""
        group = QGroupBox("📋 录制的操作")
        layout = QVBoxLayout()

        self.operations_list = QListWidget()
        self.operations_list.setFont(QFont("Consolas", 10))
        layout.addWidget(self.operations_list)

        # 鲁棒性特性说明
        info_label = QLabel(
            "✅ 自动重试 ✅ 智能等待 ✅ 多种策略\n"
            "✅ 失败截图 ✅ 详细日志 ✅ 异常恢复"
        )
        info_label.setStyleSheet("QLabel { background-color: #e8f5e9; padding: 10px; border-radius: 5px; }")
        layout.addWidget(info_label)

        group.setLayout(layout)
        return group

    def create_code_panel(self):
        """创建代码显示面板"""
        group = QGroupBox("💻 生成的鲁棒代码")
        layout = QVBoxLayout()

        self.code_text_edit = QTextEdit()
        self.code_text_edit.setReadOnly(True)
        self.code_text_edit.setFont(QFont("Consolas", 9))
        self.code_text_edit.setPlainText("# 点击「开始录制」生成超鲁棒代码...\n# 特性：自动重试、智能等待、多种策略、失败截图、详细日志")

        layout.addWidget(self.code_text_edit)
        group.setLayout(layout)
        return group

    def start_recording(self):
        """开始录制"""
        self.operations.clear()
        self.operations_list.clear()
        self.code_text_edit.setPlainText("# 录制中...\n")

        self.recorder_thread = RobustRecorderThread()
        self.recorder_thread.operation_detected.connect(self.on_operation_recorded)
        self.recorder_thread.status_changed.connect(self.on_status_changed)
        self.recorder_thread.start()

        self.start_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)
        self.statusBar().showMessage("🔴 录制中...")

    def stop_recording(self):
        """停止录制"""
        if self.recorder_thread:
            self.recorder_thread.stop()
            self.recorder_thread.quit()
            self.recorder_thread.wait()

        self.start_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self.statusBar().showMessage(f"录制已停止 - 共 {len(self.operations)} 个操作")

        self.regenerate_code()

    def on_operation_recorded(self, op: dict):
        """操作被录制"""
        self.operations.append(op)

        action = op['action']
        control_name = op['props'].get('Name', 'Unknown')
        if action == 'type':
            text = op.get('text', '')[:20]
            item_text = f"[{len(self.operations)}] {action}: \"{text}...\""
        else:
            item_text = f"[{len(self.operations)}] {action}: {control_name}"

        self.operations_list.addItem(item_text)
        self.operations_list.scrollToBottom()

    def on_status_changed(self, status: str):
        """状态变化"""
        self.statusBar().showMessage(status)

    def regenerate_code(self):
        """重新生成代码"""
        if not self.operations:
            return

        max_retry = self.max_retry_spin.value()
        retry_delay = float(self.retry_delay_spin.value())
        operation_delay = float(self.operation_delay_spin.value())

        code = RobustCodeGenerator.generate_complete_script(
            self.operations, max_retry, retry_delay, operation_delay)

        self.code_text_edit.setPlainText(code)

    def copy_code(self):
        """复制代码"""
        code = self.code_text_edit.toPlainText()
        if code:
            try:
                pyperclip.copy(code)
                self.statusBar().showMessage("✅ 代码已复制到剪贴板", 3000)
            except Exception as e:
                QMessageBox.warning(self, "错误", f"复制失败: {str(e)}")

    def save_code(self):
        """保存代码"""
        code = self.code_text_edit.toPlainText()
        if not code or code.startswith("# 点击"):
            QMessageBox.warning(self, "提示", "没有可保存的代码")
            return

        filename, _ = QFileDialog.getSaveFileName(
            self, "保存代码", f"automation_robust_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py",
            "Python Files (*.py)")

        if filename:
            try:
                with open(filename, 'w', encoding='utf-8') as f:
                    f.write(code)
                self.statusBar().showMessage(f"✅ 代码已保存到: {filename}", 3000)
            except Exception as e:
                QMessageBox.critical(self, "错误", f"保存失败: {str(e)}")

    def clear_operations(self):
        """清空操作"""
        reply = QMessageBox.question(
            self, "确认", "确定要清空所有录制的操作吗？",
            QMessageBox.Yes | QMessageBox.No)

        if reply == QMessageBox.Yes:
            self.operations.clear()
            self.operations_list.clear()
            self.code_text_edit.setPlainText("# 点击「开始录制」生成超鲁棒代码...")
            self.statusBar().showMessage("🗑️ 已清空所有操作")

    def closeEvent(self, event):
        """关闭窗口"""
        if self.recorder_thread and self.recorder_thread.is_recording:
            self.stop_recording()
        event.accept()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = RobustRecorderWindow()
    window.show()
    sys.exit(app.exec_())
